### ISSUE TITLE
Import `ocaml.org` content

### ISSUE THREAD

**Issue by tmattio** [ocaml/ood#23]
Meta-issue to track the migration of the content from the current `ocaml.org` website.

This only tracks the addition of the data in `ood` and the design phase, not the actual integration of the page in `v3.ocaml.org`.

- [ ] 99 Problems (#15)
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Releases (#18)
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Success stories (#17)
  - [X] Data added (#20)
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Books (#16)
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Videos
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Papers
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Events
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Tutorials
  - [X] Data added (#14)
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Meetings
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Companies
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Consortium
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

- [ ] Best known methods (new content)
  - [ ] Data added
  - [ ] Design/Prototype ready
  - [ ] Design agreed on

**Comment by tmattio** [comment]
@patricoferris This is my current understanding of what we need to import, but most likely missing a lot of things! Feel free to edit the issue directly to update anything missing/wrong!

Also, for each content to migrate, I propose, as a workflow, to validate the addition of the data, a first preview prototype, and the agreement of the design of the page displaying the content. This is only a proposal, let me know if you think of a workflow more appropriate to the task 🙂

**Comment by tmattio** [comment]
Also, you've already started the migration of events, videos, papers and tutorials, but I don't know if they are complete yet?

**Comment by tmattio** [comment]
@patricoferris Just to confirm: is the data import for Videos and Events complete?

**Comment by patricoferris** [comment]
Nope still more events to do (I'll do them now). Videos are more difficult because they're dispersed across the site, I'll grep for `iframe`s and make sure we've got all the referenced ones in watch.ocaml.org and then in here :))

**Comment by tmattio** [comment]
Cool, no rush, just wanted to confirm 🙂

**Comment by tmattio** [comment]
In order to be a bit more granular and accurate, I listed the pages in ocaml/ocaml.org and identified the ones we already imported and the one we won't import.

> As of 31/09/21 (0cd3d72)

- [X] ~~404.md~~ (won't import)
- [X] ~~about.fr.md~~ (won't import)
- [X] ~~about.md~~ (won't import)
- [X] ~~contributors.fr.md~~ (won't import)
- [X] ~~contributors.md~~ (won't import)
- [X] ~~governance.md~~ (won't import)
- [X] ~~index.fr.md~~ (won't import)
- [X] ~~index.md~~ (won't import)
- [ ] caml-light/faq.md
- [ ] caml-light/index.md
- [ ] caml-light/license.md
- [ ] caml-light/releases/0.75.md
- [ ] caml-light/releases/index.md
- [ ] community/announcements/CompCert_award.md
- [ ] community/cwn/index.md
- [ ] community/history/forge.md
- [ ] community/index.fr.md
- [ ] community/index.md
- [ ] community/mailing_lists.fr.md
- [ ] community/mailing_lists.md
- [ ] community/media.md
- [ ] community/planet.md
- [ ] community/planet/index.md
- [ ] community/planet/older.md
- [ ] community/planet/syndication.md
- [ ] community/support.fr.md
- [ ] community/support.md
- [ ] consortium/index.fr.md
- [X] consortium/index.md (ocaml/ood#33)
- [ ] docs/cheat_sheets.md
- [ ] docs/consortium-license.fr.md
- [ ] docs/consortium-license.md
- [ ] docs/index.fr.md
- [ ] docs/index.md
- [ ] docs/install.fr.md
- [ ] docs/install.md
- [ ] docs/license.fr.md
- [ ] docs/license.md
- [ ] docs/logos.md
- [X] docs/papers.md (ocaml/ood#11)
- [X] learn/books.md (ocaml/ood#21)
- [X] learn/companies.md (ocaml/ood#26)
- [ ] learn/description.md
- [ ] learn/faq.md
- [ ] learn/history.fr.md
- [ ] learn/history.md
- [X] ~~learn/index.fr.md~~ (won't import)
- [X] ~~learn/index.md~~ (won't import)
- [ ] learn/libraries.md
- [ ] learn/portability.md
- [X] learn/success.fr.md (ocaml/ood#20)
- [X] learn/success.md (ocaml/ood#20)
- [ ] learn/taste.fr.md
- [ ] learn/taste.md
- [X] learn/teaching-ocaml.md (ocaml/ood#37)
- [ ] learn/tutorials/99problems.md (ocaml/ood#15)
- [X] learn/tutorials/a_first_hour_with_ocaml.md (ocaml/ood#14)
- [X] learn/tutorials/calling_c_libraries.md (ocaml/ood#14)
- [X] learn/tutorials/calling_fortran_libraries.md (ocaml/ood#14)
- [X] learn/tutorials/camlp5.md (ocaml/ood#14)
- [X] ~~learn/tutorials/command-line_arguments.ja.md~~ (won't import)
- [X] learn/tutorials/command-line_arguments.md (ocaml/ood#14)
- [X] ~~learn/tutorials/command-line_arguments.zh.md~~ (won't import)
- [ ] learn/tutorials/common_error_messages.fr.md 
- [X] ~~learn/tutorials/common_error_messages.ja.md~~ (won't import)
- [X] learn/tutorials/common_error_messages.md (ocaml/ood#14)
- [X] ~~learn/tutorials/common_error_messages.zh.md~~ (won't import)
- [X] ~~learn/tutorials/comparison_of_standard_containers.ja.md~~ (won't import)
- [X] ~~learn/tutorials/comparison_of_standard_containers.ko.md~~ (won't import)
- [X] learn/tutorials/comparison_of_standard_containers.md (ocaml/ood#14)
- [X] ~~learn/tutorials/comparison_of_standard_containers.zh.md~~ (won't import)
- [X] ~~learn/tutorials/compiling_ocaml_projects.ja.md~~ (won't import)
- [X] learn/tutorials/compiling_ocaml_projects.md (ocaml/ood#14)
- [ ] learn/tutorials/data_types_and_matching.fr.md 
- [X] ~~learn/tutorials/data_types_and_matching.it.md~~ (won't import)
- [X] ~~learn/tutorials/data_types_and_matching.ja.md~~ (won't import)
- [X] learn/tutorials/data_types_and_matching.md (ocaml/ood#14)
- [X] ~~learn/tutorials/data_types_and_matching.zh.md~~ (won't import)
- [X] learn/tutorials/debug.md (ocaml/ood#14)
- [X] learn/tutorials/error_handling.md (ocaml/ood#14)
- [X] ~~learn/tutorials/file_manipulation.ja.md~~ (won't import)
- [X] learn/tutorials/file_manipulation.md (ocaml/ood#14)
- [X] ~~learn/tutorials/file_manipulation.zh.md~~ (won't import)
- [ ] learn/tutorials/format.fr.md 
- [X] learn/tutorials/format.md (ocaml/ood#14)
- [ ] learn/tutorials/functional_programming.fr.md 
- [X] ~~learn/tutorials/functional_programming.it.md~~ (won't import)
- [X] ~~learn/tutorials/functional_programming.ja.md~~ (won't import)
- [X] learn/tutorials/functional_programming.md (ocaml/ood#14)
- [X] ~~learn/tutorials/functional_programming.zh.md~~ (won't import)
- [X] learn/tutorials/functors.md (ocaml/ood#14)
- [X] ~~learn/tutorials/garbage_collection.ja.md~~ (won't import)
- [X] learn/tutorials/garbage_collection.md (ocaml/ood#14)
- [X] ~~learn/tutorials/garbage_collection.zh.md~~ (won't import)
- [X] learn/tutorials/guidelines.md (ocaml/ood#14)
- [X] ~~learn/tutorials/hashtbl.ja.md~~ (won't import)
- [X] learn/tutorials/hashtbl.md (ocaml/ood#14)
- [X] ~~learn/tutorials/hashtbl.zh.md~~ (won't import)
- [X] learn/tutorials/humor_proof.md (ocaml/ood#14)
- [ ] learn/tutorials/if_statements_loops_and_recursion.fr.md 
- [X] ~~learn/tutorials/if_statements_loops_and_recursion.it.md~~ (won't import)
- [X] ~~learn/tutorials/if_statements_loops_and_recursion.ja.md~~ (won't import)
- [X] ~~learn/tutorials/if_statements_loops_and_recursion.ko.md~~ (won't import)
- [X] learn/tutorials/if_statements_loops_and_recursion.md (ocaml/ood#14)
- [X] ~~learn/tutorials/if_statements_loops_and_recursion.zh.md~~ (won't import)
- [X] ~~learn/tutorials/index.de.md~~ (won't import)
- [ ] learn/tutorials/index.fr.md 
- [X] ~~learn/tutorials/index.it.md~~ (won't import)
- [X] ~~learn/tutorials/index.ja.md~~ (won't import)
- [X] ~~learn/tutorials/index.ko.md~~ (won't import)
- [X] learn/tutorials/index.md (ocaml/ood#14)
- [X] ~~learn/tutorials/index.zh.md~~ (won't import)
- [X] learn/tutorials/introduction_to_gtk.md (ocaml/ood#14)
- [X] ~~learn/tutorials/labels.ja.md~~ (won't import)
- [X] learn/tutorials/labels.md (ocaml/ood#14)
- [X] ~~learn/tutorials/labels.zh.md~~ (won't import)
- [X] learn/tutorials/lists.md (ocaml/ood#14)
- [ ] learn/tutorials/map.fr.md 
- [X] ~~learn/tutorials/map.ja.md~~ (won't import)
- [X] learn/tutorials/map.md (ocaml/ood#14)
- [X] ~~learn/tutorials/map.zh.md~~ (won't import)
- [ ] learn/tutorials/modules.fr.md 
- [X] ~~learn/tutorials/modules.ja.md~~ (won't import)
- [X] ~~learn/tutorials/modules.ko.md~~ (won't import)
- [X] learn/tutorials/modules.md (ocaml/ood#14)
- [X] ~~learn/tutorials/modules.zh.md~~ (won't import)
- [ ] learn/tutorials/null_pointers_asserts_and_warnings.fr.md 
- [X] ~~learn/tutorials/null_pointers_asserts_and_warnings.it.md~~ (won't import)
- [X] ~~learn/tutorials/null_pointers_asserts_and_warnings.ja.md~~ (won't import)
- [X] learn/tutorials/null_pointers_asserts_and_warnings.md (ocaml/ood#14)
- [X] ~~learn/tutorials/null_pointers_asserts_and_warnings.zh.md~~ (won't import)
- [X] ~~learn/tutorials/objects.ja.md~~ (won't import)
- [X] learn/tutorials/objects.md (ocaml/ood#14)
- [X] ~~learn/tutorials/objects.zh.md~~ (won't import)
- [X] ~~learn/tutorials/performance_and_profiling.ja.md~~ (won't import)
- [X] learn/tutorials/performance_and_profiling.md (ocaml/ood#14)
- [X] learn/tutorials/performance_and_profiling_discussion.md (ocaml/ood#14)
- [X] learn/tutorials/pointers.md (ocaml/ood#14)
- [X] ~~learn/tutorials/pointers.zh.md~~ (won't import)
- [ ] learn/tutorials/set.fr.md 
- [X] ~~learn/tutorials/set.ja.md~~ (won't import)
- [X] learn/tutorials/set.md (ocaml/ood#14)
- [X] ~~learn/tutorials/set.zh.md~~ (won't import)
- [X] learn/tutorials/streams.md (ocaml/ood#14)
- [X] learn/tutorials/up_and_running.md (ocaml/ood#14)
- [X] ~~meetings/index.fr.md~~ (won't import)
- [X] meetings/index.md (#111)
- [X] meetings/ocaml/2008/index.md (#111)
- [X] meetings/ocaml/2009/index.md (#111)
- [X] meetings/ocaml/2010/index.md (#111)
- [X] meetings/ocaml/2011/index.md (#111)
- [X] meetings/ocaml/2012/index.md (#111)
- [X] meetings/ocaml/2013/call.md (#111)
- [X] meetings/ocaml/2013/index.md (#111)
- [X] meetings/ocaml/2013/program.md (#111)
- [X] meetings/ocaml/2013/talks/index.md (#111)
- [X] meetings/ocaml/2014/cfp.md (#111)
- [X] meetings/ocaml/2014/index.md (#111)
- [X] meetings/ocaml/2014/ocaml2014_10.md (#111)
- [X] meetings/ocaml/2014/program.md (#111)
- [X] meetings/ocaml/2015/cfp.md (#111)
- [X] meetings/ocaml/2015/index.md (#111)
- [X] meetings/ocaml/2015/program.md (#111)
- [X] meetings/ocaml/2016/index.md (#111)
- [X] meetings/ocaml/2017/index.md (#111)
- [X] meetings/ocaml/2018/index.md (#111)
- [X] meetings/ocaml/2019/index.md (#111)
- [X] meetings/ocaml/2020/index.md (#111)
- [ ] ocamllabs/index.md
- [X] platform/index.md (ocaml/ood#34)
- [ ] platform/ocaml_on_windows.md
- [ ] releases/3.12.1.md
- [ ] releases/4.00.1.md
- [ ] releases/4.01.0.fr.md
- [ ] releases/4.01.0.md
- [ ] releases/4.02.md
- [ ] releases/4.03.md
- [ ] releases/4.04.md
- [ ] releases/4.05.md
- [ ] releases/4.06.1.md
- [ ] releases/4.06.md
- [ ] releases/4.07.0.md
- [ ] releases/4.07.1.md
- [ ] releases/4.08.0.md
- [ ] releases/4.08.1.md
- [ ] releases/4.09.0.md
- [ ] releases/4.09.1.md
- [ ] releases/4.10.0.md
- [ ] releases/4.10.1.md
- [ ] releases/4.10.2.md
- [ ] releases/4.11.0.md
- [ ] releases/4.11.1.md
- [ ] releases/4.11.2.md
- [ ] releases/4.12.0.md
- [X] ~~releases/index.fr.md~~ (won't import)
- [X] ~~releases/index.md~~ (won't import)


From this list, the biggest remaining tasks seem to be:

- Import the french versions of the tutorials
- Import the releases
- Import the meetings
- French translation of the companies/consortium

That's pretty much in line with the task list we previously had.

But there are also quite some pages that we didn't discuss before (I think):

- caml-light/**
- ocamllabs/index.md
- community/announcements/CompCert_award.md
- community/cwn/index.md
- community/history/forge.md
- community/index.fr.md
- community/index.md
- community/mailing_lists.fr.md
- community/mailing_lists.md
- community/media.md
- community/planet.md
- community/planet/index.md
- community/planet/older.md
- community/planet/syndication.md
- community/support.fr.md
- community/support.md
- consortium/index.fr.md
- docs/cheat_sheets.md
- docs/consortium-license.fr.md
- docs/consortium-license.md
- docs/index.fr.md
- docs/index.md
- docs/install.fr.md
- docs/install.md
- docs/license.fr.md
- docs/license.md
- docs/logos.md
- learn/description.md
- learn/faq.md
- learn/history.fr.md
- learn/history.md
- learn/libraries.md
- learn/portability.md
- learn/taste.fr.md
- learn/taste.md

@patricoferris do you have an idea of where each of these falls: do we want to ignore them, or import them?
